from services.gemini_api import get_ai_feedback

def generate_adaptive_quiz(topic: str, level: str) -> str:
    prompt = f"""
    Create a {level}-level multiple-choice question on the topic '{topic}'.
    Include 4 options and indicate the correct answer.
    Format:
    Question: ...
    A. ...
    B. ...
    C. ...
    D. ...
    Answer: ...
    """
    return get_ai_feedback(prompt)
